---
development:
  cloud_name: dzziw4hak
  api_key: '614731517319522'
  api_secret: DN2ds0rG0vh0FFbFLztMw_3Dx38
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dzziw4hak
  api_key: '614731517319522'
  api_secret: DN2ds0rG0vh0FFbFLztMw_3Dx38
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dzziw4hak
  api_key: '614731517319522'
  api_secret: DN2ds0rG0vh0FFbFLztMw_3Dx38
  enhance_image_tag: true
  static_file_support: false
